config/routes.rb
require 'sidekiq/web'
Frundraise::Application.routes.draw do
  mount RailsAdmin::Engine => '/super_admin', as: 'rails_admin'
  devise_for :users, 
    path_names: { sign_in: "login", sign_out: "logout" },
    controllers: { omniauth_callbacks: "omniauth_callbacks",registrations: 'registrations' }

  get 'dashboard' => 'dashboard#index', as: :dashboard

  resources :training_logs

  resources :fundraisers do
    member do
      get :publish, as: :publish
    end

    resources :donations
  end

  resources :charities do
    collection do
      get :info, as: :info
      get :my, as: :my
    end

    member do
      get :connect_with_stripe, as: :connect_with_stripe
      get :stripe_connected, as: :stripe_connected
      post :suspend
      post :unsuspend
      get :invite
      post :send_invite
      get :claim
      post :merge_charity
      post :own
    end
  end

  resources :donations

  resources :events do
    collection do 
      get :confirmation
    end
  end
  resources :users
  resources :feedbacks

  root 'home#index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'
  get 'how-it-works' => 'pages#how-it-works'
   Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'admin' && password == 'admin123'
  end
  mount Sidekiq::Web => '/sidekiq_workers'

end

app/models/fundraiser.rb
class Fundraiser < ActiveRecord::Base
  mount_uploader :image, ProfileUploader

  has_many :donations,:dependent=>:destroy
  has_many :training_logs,:dependent=>:destroy
  belongs_to :user
  belongs_to :charity
  belongs_to :event
  validates_presence_of :name

  accepts_nested_attributes_for :charity
  accepts_nested_attributes_for :event

  delegate :fee_percentage,to: :charity
  after_destroy :delete_all_activities
  PER_MILE_DONATION_SUGGESTIONS = (1..10).map do |n| 
    n = (n/10.0).round(2)
    OpenStruct.new(amount: n, label: "$#{ sprintf('%.2f', n)}")
  end

  scope :published, -> { where(status: 'published') }
  scope :active_event_fundraisers, -> { joins(:event).where("events.happens_on >= ?",Date.today) }
  scope :active_event_fundraiser_donation, -> { joins(:event).where("events.happens_on >= ?",Date.today-10.days) }

  def update_donation_totals
    amount = 0
    self.donations.each do |donation|
      donation.update_total!
      amount += donation.total
    end
    self.update_attribute :total_donations, amount
  end

  def total_miles
    self.training_logs.sum(&:miles)
  end

  def status?
    self.status
  end

  def published?
    self.status == 'published'
  end

  def completed?
    self.update_attributes(:status=>"completed") if self.event.happens_on < Date.today-10.days
    self.status == "completed"
  end

  def draft?
    self.status == 'draft'
  end
  
  def raised
    predict_total_donations
  end

  def predict_pledge_donation
    sum = 0
    self.donations.initial_pledges.map{|d| sum = sum + d.predicate_pledge_donation}
    sum
  end

  def predict_total_donations
    self.donations.non_pledge_donations.map {|d| d.predict_total_donation}.sum
  end

  def process_pledge_donation
    self.donations.initial_pledges.each do |donation|
      begin
        donation.make_pledge_donations
      rescue => e
        CharityMailer.donation_exception(donation,e).deliver
      end  
    end
  end

  def delete_all_activities
    Activity.where("(meta_data -> 'fundraiser_id')::int in (?)",id).delete_all
  end

  rails_admin do     
    include_all_fields
    field :created_at
  end
end

app/controllers/fundraisers_controller.rb
class FundraisersController < ApplicationController
  
  before_filter :authenticate_user!, only: [:new, :index]
  layout 'dashboard', only: [ :index] 
  def index
    if current_user.admin?
      @fundraisers = Fundraiser.all
    elsif current_user.charity_admin?
      charity_ids = current_user.charities.pluck(:id)
      @fundraisers = Fundraiser.where("charity_id in (?)",charity_ids).published
    end
    # @support_fundraisers = Fundraiser.where("id in (?)",current_user.donations.pluck(:fundraiser_id).uniq)
    @my_fundraisers = current_user.fundraisers

  end

  def new
    @fundraiser = current_user.fundraisers.new
    @fundraiser.build_charity
    @fundraiser.build_event
    @charity = Charity.find(params[:charity_id]) if params[:charity_id].present?
    @event = Event.find(params[:event_id]) if params[:event_id].present?
  end

  def create
    
    @fundraiser = current_user.fundraisers.new(fundraiser_params)
    @fundraiser.charity = Charity.new(charity_params) if @fundraiser.charity_id.blank?
    @fundraiser.event = Event.new(event_params) if @fundraiser.event_id.blank?
    if @fundraiser.save
      respond_to do |format|
        format.html { redirect_to @fundraiser }
      end
    else
      if params[:fundraiser][:from_event_page].present?
        @event = Event.find_by_id(params[:fundraiser][:event_id])
        @charity = Charity.find_by_id(params[:fundraiser][:charity_id])
      end

      respond_to do |format|
        format.html { render 'new' }
      end
    end
  end

  def show
    @fundraiser = Fundraiser.find(params[:id])
    page = params[:page] || 1
    raise ActiveRecord::RecordNotFound if  @fundraiser.draft? and current_user and current_user != @fundraiser.user and  !current_user.admin?
    @training_logs = @fundraiser.training_logs.order("created_at desc").page(page).per(10)
    # @fundraiser.story = 'Write a short story here.' if @fundraiser.story.blank?
    @can_edit = user_signed_in? && current_user.id == @fundraiser.user_id
    flash[:notice] = "This fundraiser is completed." if @fundraiser.completed?
  end

  def update
    @fundraiser = current_user.fundraisers.where(id: params[:id]).first
    @fundraiser.update_attributes(fundraiser_params)
    respond_to do |format|
      format.html { redirect_to @fundraiser }
      format.json {respond_with_bip(@fundraiser)}
    end
  end

  def publish
    @fundraiser = current_user.fundraisers.where(id: params[:id]).first!
    if @fundraiser.charity.connected_with_stripe?
      @fundraiser.update_attribute :status, 'published'
      redirect_to @fundraiser, notice: 'Your fundraiser is now live!'
    else
      redirect_to @fundraiser, error: "We can't publish your fundraiser yet. Your chosen charity has not completed the registration process yet."
    end
  end

  private

  def fundraiser_params
    params.require(:fundraiser).permit(:name, :goal, :weekly_mileage, :image, :description, :charity_id, :event_id, :story, :user_id)
  end

  def charity_params
    params.require(:fundraiser).require(:charity_attributes).permit(:name, :contact, :phone, :website, :email, :other, :description)
  end

  def event_params
    
    event_attributes = params.require(:fundraiser).require(:event_attributes).permit(:name, :happens_on)
    event_attributes[:happens_on] =  Date.parse(event_attributes[:happens_on]) rescue nil
    event_attributes

  end
end

app/helpers/fundraisers_helper.rb
module FundraisersHelper
  def show_inline_story_heading(v)
    if v.blank? 
      link_to "Write a short story here.","#"
    else
      simple_format(v)
    end  
  end

  def can_edit_training_log?(training_log)
    training_log.created_at+1.hour >= Time.now && current_user == training_log.fundraiser.user 
  end
end

app/views/fundraisers/index.html.haml
.gray.p30
  .container.white.r10
    .row
      .col-sm-12
        %h1 Fundraisers

        - if @my_fundraisers.present?

          %h3 My Fundraisers
          %table.table
            %tr
              %th Name
              %th Event
              %th Athlete
              %th Charity
              %th Raised
              %th Status

            - @my_fundraisers.each do |fundraiser|
              %tr
                %td= link_to fundraiser.name,fundraiser
                %td= link_to fundraiser.event.name,event_path(fundraiser.event) if fundraiser.event
                %td= fundraiser.user.full_name
                %td= link_to fundraiser.charity.name,charity_path(fundraiser.charity) if fundraiser.charity
                %td= number_to_currency(fundraiser.raised)
                %td= fundraiser.status

        - if @fundraisers.present?

          %h3 All Fundraisers
          %table.table
            %tr
              %th Name
              %th Event
              %th Athlete
              %th Email
              %th Charity
              %th Raised
              %th Status

            - @fundraisers.each do |fundraiser|
              %tr
                %td
                  - if fundraiser.draft? && !current_user.admin?
                    = fundraiser.name
                  - else  
                    = link_to fundraiser.name,fundraiser
                %td= link_to fundraiser.event.name ,event_path(fundraiser.event) if fundraiser.event
                %td= fundraiser.user.full_name if fundraiser.user
                %td= fundraiser.user.email if fundraiser.user
                %td= link_to fundraiser.charity.name,charity_path(fundraiser.charity) if fundraiser.charity
                %td= number_to_currency(fundraiser.raised)
                %td= fundraiser.status

app/views/fundraisers/new.html.haml
- content_for :body_class, 'fundraisers new'
.gray.p30
  .container
    .row
      .col-sm-6.col-sm-offset-3.white.r10
        .p30
          %h1.text-center Start a Fundraiser

          - if @fundraiser.errors.any?
            .bs-callout.bs-callout-danger
              %h3 We could not create your fundraiser because it had the following errors:
              %ul
                -
                - @fundraiser.errors.full_messages.each do |error_msg|
                  - error_msg = error_msg.gsub("Event happens on ","")
                  %li= error_msg

          = form_for @fundraiser do |f|
            .form-group
              = f.label "name *"
              = f.text_field :name, class: 'form-control', placeholder: "Ex. #{current_user.name}'s Run"

            - unless @fundraiser.new_record?
              .form-group
                = f.label :goal
                .input-group
                  %span.input-group-addon $
                  = f.text_field :goal, class: 'form-control', placeholder: 'Ex. 1000.00'

              .form-group
                = f.label "Anticipated Weekly Mileage"
                = f.text_field :weekly_mileage, class: 'form-control', placeholder: "Anticipated Weekly Mileage"
              
              .form-group
                = f.label :image
                = f.file_field :image, class: 'form-control'
            
            .form-hidden
              = f.hidden_field :charity_id
              = f.hidden_field :event_id
              - if (params[:charity_id].present? || @event.present?)
                = f.hidden_field :from_event_page, value: true
            
            .fundraiser_charity
              .form-group
                = label_tag "charity *"
                = text_field_tag :charity, '', name: nil, placeholder: 'Search for charity by name. Ex. American Red Cross', class: 'form-control', autocomplete: 'off'
              
              .charities_container
              .new_resource.hide
                = f.fields_for :charity do |charity_form|
                  .form-group
                    = charity_form.label :name, 'Charity Name *'
                    = charity_form.text_field :name, class: 'form-control'
                  .form-group
                    = charity_form.label :contact, 'Contact Name'
                    = charity_form.text_field :contact, class: 'form-control'
                  .form-group
                    = charity_form.label :phone
                    = charity_form.text_field :phone, class: 'form-control'
                  .form-group
                    = charity_form.label :email, 'Email'
                    = charity_form.text_field :email, class: 'form-control'
                  .form-group
                    = charity_form.label :website, 'Website'
                    = charity_form.text_field :website, class: 'form-control'  
                  .form-group
                    = charity_form.label :description, 'Any other info'
                    = charity_form.text_field :description, class: 'form-control'
            
            .fundraiser_event
              .form-group
                = label_tag "event *"
                = text_field_tag :event, '', name: nil, placeholder: 'Search for your event by name. Ex. Boston Marathon', class: 'form-control', autocomplete: 'off'
              .events_container
              .new_resource.hide
                = f.fields_for :event do |event_form|
                  .form-group
                    = event_form.label :name, 'Event'
                    = event_form.text_field :name, class: 'form-control'
                  .form-group
                    = event_form.label :happens_on
                    = event_form.text_field :happens_on, class: 'form-control datepicker'
                  
            .form-action
              = f.submit "Start My Fundraiser", class: 'btn btn-success btn-exlg', style: 'width: 80%; text-align: center; margin: auto; display: block;'

:javascript
  $(document).ready( function() {
    if(#{@charity.present?}){
      $("#fundraiser_charity_id").val("#{@charity.try(:id)}")
      $("#fundraiser_event_id").val("#{@event.try(:id)}")
      $("#event").val("#{@event.try(:name)}")
      $("#charity").val("#{@charity.try(:name)}")
      $("#charity").attr('disabled','disabled')
      if(#{@event.present?})
        $("#event").attr('disabled','disabled')
      }
  } );

app/views/fundraisers/show.html.haml
- content_for :body_class, "fundraisers fundraiser_#{@fundraiser.id} show"
- content_for :social_title, @fundraiser.name
- content_for :social_image, @fundraiser.image.url(:profile)

- if @fundraiser.draft? && current_user == @fundraiser.user
  .publish_bar{ style: 'background: #32020f; color: white; padding: 10px;' }
    .container
      .pull-right
        = link_to 'Publish Fundraiser', [:publish, @fundraiser], class: "btn btn-success #{'disabled' if !@fundraiser.charity.connected_with_stripe? || current_user != @fundraiser.user}"

      %h4{ style: 'margin: 5px 0;'} Your fundraiser is currently saved as a draft. 
      - unless @fundraiser.charity.connected_with_stripe?
        %div{ style: 'max-width: 650px;'}
          However, you can't publish it yet because your chosen charity has not completed the registration process. We will be getting in touch with them soon to walk them through the process.
          

.gray.p30
  .container.white.r10
    .row
      .col-sm-6
        - if @fundraiser.image.url.present?
          .image{style: 'margin-bottom: 10px;'}
            = image_tag @fundraiser.image.url(:profile)
        -else
          =image_tag("fundraiser-logo.png")    

        - if @fundraiser.user == current_user
          = form_for @fundraiser,:html=>{:class=>"validate_form"} do |f|
            = f.file_field :image, class: 'form-control required', style: 'margin-bottom: 5px;',"data-msg-required"=>"You must choose a new file before you can update the image"
            %div
              = f.submit "Update Image", class: 'btn btn-primary'
              %span.text-muted (only jpg, jpeg, gif, png file)

      .col-sm-6
        %h1
          = best_in_place_if @can_edit, @fundraiser, :name, type: :input
          %br/
          - if @fundraiser.published?
            :erb
              <div id="fb-root"></div>
              <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=868321799980028";
                fjs.parentNode.insertBefore(js, fjs);
              }(document, 'script', 'facebook-jssdk'));</script>
            %div{ class: "fb-share-button", data: { href: fundraiser_url(@fundraiser), type: "button_count"} }
            %a{ href: "https://twitter.com/share", class: "twitter-share-button", data: { via: "Frundraise" }} Tweet
            :erb
              <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
              
              <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
              <g:plusone></g:plusone>
        
        %h4
          Event: 
          = "#{@fundraiser.event.name} on #{@fundraiser.event.happens_on.to_s(:long)}"
        
        %h4
          Total Miles: 
          = pluralize(@fundraiser.total_miles, 'Mile')

        -if @fundraiser.user == current_user
          %h4
            Anticipated Weekly Mileage:
            -if @can_edit
              = best_in_place_if @can_edit, @fundraiser, :weekly_mileage, type: :input           
            -else
              = @fundraiser.weekly_mileage.blank? ? 'Not Mentioned' : "#{@fundraiser.weekly_mileage} miles"
          
        %h4
          Fundraising Goal:
          -if @can_edit
            = best_in_place_if @can_edit, @fundraiser, :goal, type: :input, display_with: :number_to_currency           
          -else
            = @fundraiser.goal.blank? ? 'Not Mentioned' : number_to_currency(@fundraiser.goal)

        %h4
          Amount Raised:
          = number_to_currency(@fundraiser.raised)
      
        = link_to "Support #{@fundraiser.user.display_first_name}", [:new, @fundraiser, :donation], class: "btn btn-lg btn-success #{'disabled' if !@fundraiser.charity.connected_with_stripe? || @fundraiser.draft?}", data: { 'no-turbolink' => ''},disabled: @fundraiser.completed?
        -if @can_edit && @fundraiser.published?
          %button.btn.btn-success.btn-lg{"data-target" => "#log_miles_modal", "data-toggle" => "modal",disabled: @fundraiser.completed?} Log Miles
          
      .col-sm-8
        %h3= "#{@fundraiser.user.display_first_name}'s Story"
        = best_in_place_if @can_edit, @fundraiser, :story, type: :textarea,:nil=>show_inline_story_heading(nil),:display_with => lambda {|v| show_inline_story_heading(v).html_safe}
        %br
        %table.table.table-bordered
          %thead
            %tr
              %th 
                Workout Name
              %th
                Training Date
              %th Miles  
              - if @can_edit
                %th Manage
          %tbody
            - @training_logs.each do |training_log|      
              %tr
                %td
                  = training_log.workout_name
                %td
                  = training_log.training_date.to_s(:long)
                %td  
                  = training_log.miles
                - if @can_edit  
                  %td
                    - if can_edit_training_log?(training_log)
                      = link_to "Delete" ,training_log_path(training_log),:method=>:delete,data: { confirm: 'Are you sure?' },:class=>"btn btn-warning"
        = paginate @training_logs

      .col-sm-4
        .charity
          %h3= "About #{@fundraiser.user.display_first_name}'s Charity"
          .logo.r10
            - if @fundraiser.charity.logo.url.present?
              = image_tag @fundraiser.charity.logo.url(:thumb)
            -else
              =image_tag("charity-logo.jpg",:style=>"background: gray;width: 100%; height: 175px;'")  
          %h4= @fundraiser.charity.name
          %p= @fundraiser.charity.description
          %br/  
                      
        
#log_miles_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "log_miles_modal_label", role: "dialog", tabindex: "-1"}
  .modal-dialog#log_mile
    .modal-content
      = form_for(@fundraiser.training_logs.new,:html=>{:id=>"log_mile_form"})do |f|
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &#215;
          %h4#log_miles_modal_label.modal-title Log a Workout
        .modal-body
          = f.label :workout_name
          = f.text_field :workout_name,:class=>"required form-control ",:required=>true
          = f.label :miles
          = f.text_field :miles,:class=>"required form-control",:required=>true
          = f.label :training_date
          = f.text_field :training_date,:class=>"training_date required form-control",:readonly=>true,:required=>true
          = f.hidden_field :fundraiser_id,:value=>@fundraiser.id
          
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
          = f.submit 'Save Miles', class: 'btn btn-primary'
    