config/routes.rb
require 'sidekiq/web'
Frundraise::Application.routes.draw do
  mount RailsAdmin::Engine => '/super_admin', as: 'rails_admin'
  devise_for :users, 
    path_names: { sign_in: "login", sign_out: "logout" },
    controllers: { omniauth_callbacks: "omniauth_callbacks",registrations: 'registrations' }

  get 'dashboard' => 'dashboard#index', as: :dashboard

  resources :training_logs

  resources :fundraisers do
    member do
      get :publish, as: :publish
    end

    resources :donations
  end

  resources :charities do
    collection do
      get :info, as: :info
      get :my, as: :my
    end

    member do
      get :connect_with_stripe, as: :connect_with_stripe
      get :stripe_connected, as: :stripe_connected
      post :suspend
      post :unsuspend
      get :invite
      post :send_invite
      get :claim
      post :merge_charity
      post :own
    end
  end

  resources :donations

  resources :events do
    collection do 
      get :confirmation
    end
  end
  resources :users
  resources :feedbacks

  root 'home#index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'
  get 'how-it-works' => 'pages#how-it-works'
   Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'admin' && password == 'admin123'
  end
  mount Sidekiq::Web => '/sidekiq_workers'

end

app/views/shared/_dashboard_top_bar.html.haml
= link_to 'Dashboard', dashboard_path,:class=>active_class("dashboard")
- if current_user.admin?
  = link_to 'Users', users_path
- unless current_user.supporter?  
  = link_to 'Fundraisers', fundraisers_path,:class=>active_class("fundraiser")
-if current_user.admin? || current_user.charity_admin?
  = link_to 'Charities', charities_path,:class=>active_class("charity")
= link_to 'Donations', donations_path,:class=>active_class("donation")
= link_to 'Events', new_event_path,:class=>active_class("events")

app/views/shared/_top_bar.html.haml
- if user_signed_in?
  = link_to 'Dashboard', dashboard_path ,:class=>active_class("dashboard")
= link_to 'Start a Fundraiser', new_fundraiser_path,:class=>active_class("new_fundraiser")
= link_to 'How It Works', '/how-it-works',:class=>active_class("how-it-work")
= link_to 'Charities', info_charities_path,:class=>active_class("charity")
= link_to 'Events', new_event_path,:class=>active_class("events")