config/routes.rb
require 'sidekiq/web'
Frundraise::Application.routes.draw do
  mount RailsAdmin::Engine => '/super_admin', as: 'rails_admin'
  devise_for :users, 
    path_names: { sign_in: "login", sign_out: "logout" },
    controllers: { omniauth_callbacks: "omniauth_callbacks",registrations: 'registrations' }

  get 'dashboard' => 'dashboard#index', as: :dashboard

  resources :training_logs

  resources :fundraisers do
    member do
      get :publish, as: :publish
    end

    resources :donations
  end

  resources :charities do
    collection do
      get :info, as: :info
      get :my, as: :my
    end

    member do
      get :connect_with_stripe, as: :connect_with_stripe
      get :stripe_connected, as: :stripe_connected
      post :suspend
      post :unsuspend
      get :invite
      post :send_invite
      get :claim
      post :merge_charity
      post :own
    end
  end

  resources :donations

  resources :events do
    collection do 
      get :confirmation
    end
  end
  resources :users
  resources :feedbacks

  root 'home#index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'
  get 'how-it-works' => 'pages#how-it-works'
   Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'admin' && password == 'admin123'
  end
  mount Sidekiq::Web => '/sidekiq_workers'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :fundraisers

  validates_presence_of :name
  validates_presence_of :happens_on,:message=>"Please set a future date for your event"
  
  validate :happens_on_cannot_be_in_the_past
  has_many :event_charities
  has_many :charities, through: :event_charities
  
  has_one :charity_request, dependent: :destroy
  accepts_nested_attributes_for :charity_request

  scope :active_events,lambda{where("happens_on >= ?",Date.today)}
  def happens_on_cannot_be_in_the_past
    
    errors.add(:happens_on,"Please set a future date for your event") if happens_on.present? &&  happens_on < Date.today  

  end
  
  def miles_trained
    TrainingLog.where(fundraiser_id: fundraiser_ids).sum(&:miles)
  end

  def donations_total
    self.fundraisers.map{|x|x.predict_total_donations}.sum
  end

  def completed?
    self.happens_on > Date.today
  end
end

app/controllers/events_controller.rb
require 'uri'

class EventsController < ApplicationController
  before_filter :redirect_if_already_have_account,only: [:new]

  def index
    @events = Event.all
    search_query = URI.unescape(params[:query]).gsub('+', ' ') if params[:query]

    events = Event.arel_table
    
    # Doesn't work. Change to full text search.
    @events = @events.where(events[:name].matches("%#{search_query}%")).where("happens_on >= ?",Date.today) if search_query

    respond_to do |format|
      format.json{ render :json => @events.to_json }
    end
  end

  def show
    @event = Event.find(params[:id])
    fundraiser_ids = @event.fundraiser_ids
    @miles_trained = TrainingLog.where(fundraiser_id: fundraiser_ids).sum(&:miles)
    @amount_raised = Donation.where(fundraiser_id: fundraiser_ids).non_pledge_donations.map{|d| d.predict_total_donation}.sum
    @charity_partners = @event.charities.order(created_at: :desc).sort_by {|x| x.raised_for_event(@event)}.reverse.each_slice(3)
  end

  def new    
    @event = Event.new
    @event.build_charity_request
  end

  def create
    @event = Event.new(event_params)
    @event.charity_request = CharityRequest.new(charity_request_params)
    charity_request = @event.charity_request

    #event coordinator
    charity_request.user = user_signed_in? ? current_user : User.new(user_params)

    if params[:user].present? && current_user && params[:user][:phone_number].present?
      charity_request.user.phone_number = params[:user][:phone_number]
    end
    @event.valid?
    is_user_valid = charity_request.user.valid?
    charity_request.user.validate_phone_number

    if is_user_valid && @event.save
      charity_request.user.save
      sign_in charity_request.user unless user_signed_in?
      redirect_to confirmation_events_path(event_id: @event.id), notice: "Event registered successfully. We will update your event page shortly
with your Charity Partners. Please contact us at <a href='mailto:admin@frundraise.com' target='_blank'>admin@frundraise.com</a> if you have further questions."
    else
      if @event.errors.has_key? :name
        @event.errors[:name].shift
        @event.errors[:name] = "Event name can't be blank" 
      end
      render :new
    end
  end

  def confirmation
    @event = Event.find_by_id(params[:event_id])
  end

  private

  def event_params
    params.require(:event).permit(:name, :happens_on)
  end

  def user_params
    params.require(:user).permit(:first_name,:last_name,:phone_number,:email,:password,:password_confirmation)
  end

  def charity_request_params
    params.require(:event).require(:charity_request_attributes).permit(:email, :phone_number, :name, :charities)
  end

  def redirect_if_already_have_account
    if params[:login].present?
      session[:user_return_to] = new_event_path
      return redirect_to new_user_session_path
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
	def user_has_phone_number?
		!user_signed_in? || (user_signed_in? && current_user.phone_number.nil?)
	end
end

app/views/events/confirmation.html.haml
.gray.p30
  .container.white.r10{style: "min-height:450px;padding-top: 100px;"}
    .row
      .col-sm-12{style: "padding: 0px 275px;"}
        Share the following link with your athletes so that they can start their fundraisers. You can copy this link to your event registration website, in newsletter emails to the athletes, or anywhere else.
        %br
        %br
        .text-center
          = link_to event_url(@event), event_url(@event) if @event.present?
        %br
        %br  
        Are you the charity administrator for one of your charity partners? If so, 
        = link_to "create your charity profile now.", new_charity_path

app/views/events/new.html.haml
.gray.p30
  .container
    .row
      .col-sm-12.white.r10
        .p30          
          .donation_form
            .container
              .row.text-center
                .col-sm-12
                  %h1
                    Register your Event
                  Event coordinators, create your event and link it to one or more charity partners. This will create an event page where your athletes can start their fundraisers.
              %br
              %br
              .row
                .col-sm-8.col-sm-offset-2
                  %p.errors.hide{ style: "background-color: #f2dede; text-align: center; margin-bottom: 20px; padding: 15px;" } Please agree to the terms of this website by checking the box below.
                  = form_for @event, class: 'form-horizontal validate_form' do |f|
                    - if @event.errors.any? || @event.charity_request.try(:user).try(:errors).try(:any?)
                      .bs-callout.bs-callout-danger
                        %h3 We could not create your event because it had the following errors:
                      %div#error_explanation{:style=>"padding-left: 100px;"}
                        %ul
                          - if @event.errors.any?
                            - @event.errors.values.each do |msg| 
                              %li 
                                =msg.first
                          - if @event.charity_request.user.errors.any?
                            - @event.charity_request.user.errors.full_messages.each do |msg| 
                              %li 
                                =msg

                    .form-group.row#fixed_donation_container
                      = f.label :name, 'Event name:', class: 'col-sm-3 control-label text-right'
                      .col-sm-6
                        .input-group.col-sm-8
                          = f.text_field :name, class: 'form-control number required'

                    .form-group.row#fixed_donation_container
                      = f.label :happens_on,"Happens on:", class: 'col-sm-3 control-label text-right'
                      .col-sm-6
                        .input-group
                          = f.text_field :happens_on, class: 'form-control datepicker'

                    = f.fields_for :charity_request do |charity_form|
                      .form-group.row#fixed_donation_container
                        = charity_form.label :charities, 'Charity Partners:', class: 'col-sm-3 control-label text-right'
                        .col-sm-6
                          .input-group.col-sm-8
                            = charity_form.text_area :charities, class: 'form-control required'
                      %hr
                    - unless user_signed_in?
                      .form-group.row
                        .col-sm-3.text-right
                          Account Details:
                        .col-sm-6
                          = link_to "Already have an account?",new_event_path(login: true)

                      .form-group.row#pledge_donation_container
                        .col-sm-3.control-label.text-right
                        .col-sm-4
                          = text_field_tag :first_name, @event.charity_request.try(:user).try(:first_name),name: "user[first_name]" ,class: 'form-control required'
                          First name
                        .col-sm-4
                          = text_field_tag :last_name,@event.charity_request.try(:user).try(:last_name),name: "user[last_name]" ,class: 'form-control required'
                          Last name

                      .form-group.row#fixed_donation_container
                        .col-sm-3.control-label.text-right
                        .col-sm-8
                          .input-group.col-sm-12
                            = text_field_tag :email,@event.charity_request.try(:user).try(:email),name: "user[email]", class: 'form-control required'
                          Email *
                    - if user_has_phone_number?
                      .form-group.row#fixed_donation_container
                        = f.label :phone_number, 'Phone Number:', class: 'col-sm-3 control-label text-right'
                        .col-sm-6
                          .input-group.col-sm-8
                            = text_field_tag :phone_number,@event.charity_request.try(:user).try(:phone_number),name: "user[phone_number]", class: 'form-control number required'

                    - unless user_signed_in?
                      .form-group.row#fixed_donation_container
                        .col-sm-3.control-label
                        .col-sm-8
                          .input-group.col-sm-12
                            = password_field_tag :password,"",name: "user[password]",maxlength: "10", class: 'form-control number required'
                          Password *

                      .form-group.row#fixed_donation_container
                        .col-sm-3.control-label
                        .col-sm-8
                          .input-group.col-sm-12
                            = password_field_tag :password_confirmation,"",name: "user[password_confirmation]",maxlength: "10", class: 'form-control number required'
                          Password confirmation *

                    .form-group.row
                      .col-sm-9.col-sm-offset-3
                        = f.submit class: 'btn btn-success'

app/views/events/show.html.haml
- content_for :body_class, 'charities info'

.gray.p30
  .container.white.r10
    .row
      .col-sm-12
        %h1
          = "#{@event.name} on #{@event.happens_on.to_s(:long)}"
        .atheletes.text-center
          = pluralize(@event.fundraisers.published.count, 'Athlete')
        .atheletes
          
        .miles_trained.text-center
          = @miles_trained
          Total Miles
        .raised.text-center
          Total Raised:
          = number_to_currency(@amount_raised)

        - if @charity_partners.size > 0  
          %h3 Charity Partners
      .col-sm-12        
        .charities
          - @charity_partners.each_with_index do |charities, index|
            .row
              - charities.each_with_index do |charity, i|
                - if charity
                  .col-md-4
                    .charity
                      .image
                        .vertical_center
                          -if charity.logo.url.present?
                            = link_to image_tag(charity.logo.url(:profile)), charity
                          -else  
                            = link_to image_tag("charity-logo.jpg"), charity
                      .details
                        .name= link_to charity.name, charity
                        .stats
                          = number_to_currency(charity.raised_for_event(@event)) 
                          Raised  - 
                          = charity.supporters_for_event(@event)
                          Supporters
                        .support-charity
                          = link_to "Start Your Fundraiser",new_fundraiser_path(charity_id: charity.id, event_id: @event.id), class: 'btn btn-success'
      
        - if @event.fundraisers.published.present?  
          %h4 Active Fundraisers
    .row
      - @event.fundraisers.published.sort_by {|x| x.raised}.reverse.each do |fundraiser|
        %div.media.col-sm-4
          %a.pull-left{:href=>fundraiser}
            - if fundraiser.image_url.present?
              %img.media-object{:src=>fundraiser.image.url(:profile),:style=>"width: 64px; height: 64px;"}
            - else   
              =image_tag("fundraiser-logo.png",:class=>"media-object",:style=>"width: 64px; height: 64px;")
          %div.media-body
            %h5.media-heading 
              =link_to fundraiser.name,fundraiser
            %div
              Charity:
              = link_to fundraiser.charity.name,charity_path(fundraiser.charity)  
            %div
              Fundraising Goal :
              - if fundraiser.goal.blank?
                Not Mentioned
              -else 
                = number_to_currency(fundraiser.goal)        
            %div
              Amount Raised:
              = number_to_currency(fundraiser.raised)
            %div 
              Total Miles:
              = pluralize(fundraiser.total_miles, 'Mile')  
             
    
    %br