config/routes.rb
require 'sidekiq/web'
Frundraise::Application.routes.draw do
  mount RailsAdmin::Engine => '/super_admin', as: 'rails_admin'
  devise_for :users, 
    path_names: { sign_in: "login", sign_out: "logout" },
    controllers: { omniauth_callbacks: "omniauth_callbacks",registrations: 'registrations' }

  get 'dashboard' => 'dashboard#index', as: :dashboard

  resources :training_logs

  resources :fundraisers do
    member do
      get :publish, as: :publish
    end

    resources :donations
  end

  resources :charities do
    collection do
      get :info, as: :info
      get :my, as: :my
    end

    member do
      get :connect_with_stripe, as: :connect_with_stripe
      get :stripe_connected, as: :stripe_connected
      post :suspend
      post :unsuspend
      get :invite
      post :send_invite
      get :claim
      post :merge_charity
      post :own
    end
  end

  resources :donations

  resources :events do
    collection do 
      get :confirmation
    end
  end
  resources :users
  resources :feedbacks

  root 'home#index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'
  get 'how-it-works' => 'pages#how-it-works'
   Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'admin' && password == 'admin123'
  end
  mount Sidekiq::Web => '/sidekiq_workers'

end

app/models/charity.rb
class Charity < ActiveRecord::Base
  include Tokenable
  mount_uploader :logo, LogoUploader

  has_many :fundraisers,:dependent=>:destroy
  belongs_to :user
  has_many :event_charities
  has_many :events, through: :event_charities

  validates_presence_of :name

  #commenting following validation in order to allow user to have multiple charities
  #validates_uniqueness_of :user_id,:message=>"You are already the owner of one charity on Frundraise. If you would like to create a second charity, you first need to create a second account to use for that charity.",:allow_nil=>true
  validates_format_of :website, :with =>/(http|https):\/\/|[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*)?/ix,:allow_nil=>true,:allow_blank=>true
  scope :not_connected_with_stripe, -> { where(stripe_access_token: nil).where(stripe_publishable_key: nil).where(stripe_user_id: nil) }
  scope :connected_with_stripe, -> { where.not(stripe_access_token: nil).where.not(stripe_publishable_key: nil).where.not(stripe_user_id: nil) }

  scope :active, -> { where.not(user_id: nil) }
  scope :inactive, -> { where(user_id: nil) }

  before_create :save_token

  def connected_with_stripe?
    stripe_access_token.present? and stripe_user_id.present? and stripe_publishable_key.present?
  end

  def save_token
    return if self.user
    self.token = generate_token
  end

  def save_stripe_auth(auth)
    # logger.debug "Charity#save_stripe_auth"
    # logger.debug "auth = " + auth.inspect

    # logger.debug "stripe_access_token = #{auth["credentials"]["token"]}"
    # logger.debug "stripe_user_id = #{auth["uid"]}"
    # logger.debug "stripe_publishable_key = #{auth["info"]["stripe_publishable_key"]}"

    self.stripe_access_token = auth["credentials"]["token"]
    self.stripe_user_id = auth["uid"]
    self.stripe_publishable_key = auth["info"]["stripe_publishable_key"]

    valid? ? save! : logger.debug("Error occurred while saving: #{errors.full_messages.join('. ')}")
  end

  def as_json(options={})
    super(:methods => [:image_url], :only => [:id, :name, :description, :website, :address, :phone])
  end

  def raised
    Donation.where(fundraiser_id: self.fundraiser_ids).non_pledge_donations.map{|x|x.predict_total_donation}.sum
  end

  def supporters
    Donation.where(fundraiser_id: self.fundraiser_ids).count + self.fundraisers.count
  end

  def raised_for_event(event)
    fundraisers_ids = fundraisers_for_event(event).map(&:id)
    Donation.where(fundraiser_id: fundraisers_ids).non_pledge_donations.map{|x|x.predict_total_donation}.sum
  end

  def supporters_for_event(event)
    fundraisers_ids = fundraisers_for_event(event).map(&:id)
    Donation.where(fundraiser_id: fundraisers_ids).count + fundraisers_ids.count
  end

  def fundraisers_for_event(event)
    self.fundraisers.published.select{|f| f.event_id == event.id}
  end

  def image_url
    self.logo ? self.logo.url(:thumb) : ''
  end

  def active?
    connected_with_stripe?
  end
  
  def website_url

    if self.website.present?
      unless self.website[/\Ahttp:\/\//] || self.website[/\Ahttps:\/\//]
        "http://#{self.website}"
      else
        self.website  
      end
    else
     ""  
    end  
  end

  def merge_charity(in_active_charity_id)
    charity = Charity.find(in_active_charity_id)
    fundraisers = self.fundraisers+charity.fundraisers
    self.fundraisers = fundraisers.flatten.compact.uniq
    if self.save!
      charity.delete #replaced destroy with delete
      true
    else
      false  
    end
  end

  def active_fundraisers
    self.fundraisers.select{|f| f.event.happens_on >= Date.today}.compact
  end

end

app/controllers/charities_controller.rb
require 'uri'

class CharitiesController < ApplicationController

  before_filter :authenticate_user!, only: [:new, :edit, :create, :delete, :my, :claim,:destroy,:connect_with_stripe]
  layout 'dashboard', only: [:my, :index]

  def index
    
    respond_to do |format|
      format.html do
        return redirect_to root_path, alert: "You are not authorized to view this page." unless user_signed_in? # and current_user.admin?
        
        if current_user.admin?
          @active_charities = Charity.active
          @inactive_charities = Charity.inactive
        end
              
        @my_charities = current_user.charities
        
      end
    
      format.json do
        charities = Charity.arel_table
        search_query = URI.unescape(params[:query]).gsub('+', ' ') if params[:query]
        @charities = Charity.where(charities[:name].matches("%#{search_query}%")) if search_query
        render json: @charities.to_json
      end
    end
  end

  def show
    session[:charity_id_for_stripe_connect] = params[:id]
    @charity = load_charity
    @fundraisers = @charity.active_fundraisers
    @can_edit = user_signed_in? && current_user.id == @charity.user_id
  end

  def new
    @charity = Charity.new
  end

  def edit
    @charity = load_charity
    raise ActiveRecord::RecordNotFound unless current_user.admin? or current_user.id == @charity.user_id
  end

  def claim
    @charity = load_charity
    @token = params[:token]
    if @token.blank? or @charity.token != @token
      redirect_to root_path, notice: "Error: The token you utilized while trying to claim a charity is invalid."
    end
  end

  def own
    @charity = load_charity
    if @charity.token == params[:token]
      @charity.user = current_user
      @charity.save
      redirect_to [:connect_with_stripe, @charity], notice: "Congratulations. You're now the owner of this charity. Your next step is to connect with Stripe."
    else
      redirect_to root_path, notice: "Error: The token you utilized while trying to claim a charity is invalid."
    end
  end

  def invite
    raise ActiveRecord::RecordNotFound unless current_user.admin?
    @charity = load_charity
    @message = "Hi#{@charity.contact ? " #{@charity.contact}" : ''}, \n\n#{@charity.fundraisers.first.user.name} is training for the #{@charity.fundraisers.first.event.name} and wants to start a fundraiser to benefit you on Frundraise. Frundraise is a fundraising website for runners, cyclists, triathletes, and all other endurance athletes who want to raise money for charity as part of their training for an event. Before #{@charity.fundraisers.first.user.name} can start raising money for you, we need you to set up your profile on Frundraise so that you can start accepting donations. Follow the link below to get started.\n\n#{claim_charity_url(@charity, token: @charity.token)}\n\nThe Frundraise Team\nhttp://www.frundraise.com"
    @athlete = @charity.fundraisers.first.user.name
  end

  def send_invite

    raise ActiveRecord::RecordNotFound unless current_user.admin?
    @body = params[:body]
    @recipient = params[:recipient]
    @athlete = params[:athlete]
    @charity = Charity.find(params[:id])
    if @recipient.blank?
       redirect_to invite_charity_path(@charity),notice: "Recipient can't be empty"
    else
      CharityMailer.new_charity_invite(@body, @recipient, @athlete).deliver
      redirect_to charities_path, notice: "Your invite was sent."
    end  
  end

  def info
    # @charities = Charity.order(created_at: :desc).sort_by {|x| x.raised}.reverse
    charity_ids = [11, 35, 56, 94, 100]
    @charities = Charity.where("id IN (?)", charity_ids).reverse!
    if @charities.blank?
      @names = ["Ronald McDonald House Charities of Central Ohio", "Bicycles For Humanity", "Tri 4 Schools", "Friends of Amani US", "Save the Colorado"]
      @charity_names = @names.map(&:downcase)
      @charities = Charity.where("lower(name) IN (?)", @charity_names).reverse!
    end
    
    @charities = @charities.insert(2, nil)
    @charities_slices = @charities.each_slice(3)
  end

  def create
    @charity = current_user.charities.new(charity_params)
    if @charity.save
      session[:charity_id_for_stripe_connect] = params[:id]
      # redirect_to [:connect_with_stripe, @charity]
      respond_to do |format|
      format.html {redirect_to @charity}
      
      format.json { render json: @charity.errors, status: :unprocessable_entity }
    end
    else
      render 'new'
    end
  end

  def connect_with_stripe
    session[:charity_id_for_stripe_connect] = params[:id]
  end

  def stripe_connected
    @charity = load_my_charity
  end

  def my
    @charity
  end

  def suspend
    @charity = load_my_charity
    @charity.suspend!
  end

  def update
    @charity = load_charity
    raise ActiveRecord::RecordNotFound unless current_user.admin? or current_user.id == @charity.user_id
    @charity.update_attributes(charity_params)
    respond_to do |format|
      format.html {redirect_to @charity}
      
      format.json {respond_with_bip(@charity)}
    end  
  end

  def destroy
    if current_user.admin?
      @charity = Charity.find(params[:id])
      @charity.destroy

    end
    redirect_to charities_path
  end

  def merge_charity
    if current_user.admin?
      @charity = Charity.find(params[:id])
      @charity.merge_charity(params[:in_active_charity_id])
    end
    redirect_to  charities_path,:notice=>"Charity #{@charity.name} was successfully merged"
  end

  private

  def charity_params
    params.require(:charity).permit(:name, :tax_id, :website, :description, :logo, :email, :contact)
  end

  def load_my_charity
    current_user.charities.where(id: params[:id]).first
  end

  def load_charity
    Charity.find(params[:id])
  end
end

app/helpers/charities_helper.rb
module CharitiesHelper
	def show_inline_story_heading(v)
    if v.blank? 
      link_to "Write a short story here.","#"
    else
      simple_format(v)
    end  
  end
end

app/views/charities/_form.html.haml
= form_for @charity do |f|
  - if @charity.errors.any? 
    %div#error_explanation
      %h4
        = pluralize(@charity.errors.count, "error") 
        prohibited this charity from being saved

      %ul  
        - @charity.errors.full_messages.each do |msg| 
          - msg = msg.gsub("User ","")
          %li 
            =msg 


      %hr
  .form-group
    = f.label :name, 'Charity Name *'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :tax_id, 'Tax ID # / EIN #' 
    = f.text_field :tax_id, class: 'form-control'

    - unless @charity.new_record?
      - unless @charity.user
        .form-group
          = f.label :email
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.label :contact
          = f.text_field :contact, class: 'form-control'
      .form-group
        = f.label :website
        = f.text_field :website, class: 'form-control'
      .form-group
        = f.label :phone
        = f.text_field :phone, class: 'form-control'
      .form-group
        = f.label :description, 'Short Description'
        = f.text_area :description, class: 'form-control'
      .form-group
        = f.label :logo, 'Profile image (optional - can be added/changed later)'
        = f.file_field :logo, class: 'form-control'
    %br
    .form-group
      = f.submit class: 'btn btn-primary btn-lg'

app/views/charities/_merge_charity.html.haml
%div.modal{:id=>"merge_charity_#{charity.id}"}
  %div.modal-dialog
    %div.modal-content
      
      %div.modal-header
        %button.close{"data-dismiss"=>"modal","aria-hidden"=>"true"}
        %h4.modal-title= "Merge #{charity.name}"
      =form_tag(merge_charity_charity_path(charity)) do 
        %div.modal-body
          %p 
            Merge 
            %strong= charity.name 
            Charity From In Active Charities

          = select_tag :in_active_charity_id,options_from_collection_for_select(@inactive_charities,:id,:name),:class=>"form-control col-md-5"
          %br 

        %div.modal-footer
          %button.btn.btn-default{"data-dismiss"=>"modal"} Close
          =submit_tag "Merge Charity",:class=>"btn btn-primary"

app/views/charities/claim.html.haml
.gray.p30
  .container.white.r10
    .row
      .col-sm-6.col-sm-offset-3
        %h1 Claim Charity Ownership
        %p 
          Thank you for choosing to be a part of Frundraise. We hope athletes use Frundraise to raise donations to support your cause.
        = form_tag [:own, @charity] do
          = hidden_field_tag :token, @token
          = submit_tag 'Claim Ownership', class: 'btn btn-success'
    %br/

app/views/charities/connect_with_stripe.html.haml
.container
  .row
  %p Stripe is a third party credit card processor that we use to process donations on Frundraise.
  %p Create a Stripe account and connect it with your Frundraise account so that you can accept donations.
  .col-sm-12
    = link_to "Sign in with Stripe", user_omniauth_authorize_path(:stripe_connect), class: 'btn btn-lrg btn-primary'

  	

app/views/charities/edit.html.haml
.gray.p30
  .container
    .row
      .col-sm-4.col-sm-offset-4.white.r10
        %h1 Edit Charity
        = render 'form'

app/views/charities/index.html.haml
.gray.p30
  .container.white.r10
    .row
      .col-sm-12
        %h2 My Charities
        %table.table
          %tr

            %th Name
            %th Tax ID / EIN
            %th Website
            %th Phone
            %th Connected With Stripe
            %th Actions
          - @my_charities.each do |charity|
            %tr
              %td= link_to charity.name, charity
              %td= charity.tax_id
              %td= charity.website
              %td= charity.phone
              %td
                - if charity.connected_with_stripe?
                  Connected
                - else
                  Not connected
                  = link_to 'Connect Now', [:connect_with_stripe, charity]
              %td= link_to 'Edit', [:edit, charity], class: 'btn btn-default'
        
        
        - if user_signed_in? and current_user.admin? and @active_charities.any?
          %h2 Active Charities
          %table.table
            %tr
              %th Tax ID
              %th Name
              %th Contact
              %th Phone
              %th Email
              %th Website
              %th Raised
              %th Stripe Status
              %th Action

            - @active_charities.each do |charity|
              %tr
                %td= charity.tax_id 
                %td= charity.name 
                %td= charity.user.name if charity.user
                %td= charity.phone 
                %td= charity.user.email if charity.user
                %td= charity.website 
                %td= charity.connected_with_stripe? ? number_to_currency(charity.raised) : '-'
                %td= charity.connected_with_stripe? ? 'Connected' : 'Not Connected'
                %td
                  
                  %div.btn-group
                    %button.btn.btn-default.btn-info.dropdown-toggle{"data-toggle"=>"dropdown"}
                      Action
                      %span.caret
                      
                    %ul.dropdown-menu
                      %li
                        = link_to 'Edit', [:edit, charity], class: ''
                      %li  
                        / = link_to ' Delete', charity_path(charity), class: '',:method=>:delete,:confirm=>"Are you sure you want to delete charity?"
                      %li  
                        = link_to 'Merge Charity',"#", "data-toggle"=>"modal", "data-target"=>"#merge_charity_#{charity.id}"
              = render :partial=>"merge_charity",:locals=>{:charity=>charity}    

        - if current_user.admin? && @inactive_charities.any?
          %h2 Inactive Charities
          %table.table
            %tr
              %th Tax ID
              %th Name
              %th Contact
              %th Phone
              %th Email
              %th Website
              %th Any other Info
              %th{ style: 'width: 20%'} Action
            - @inactive_charities.each do |charity|
              %tr
                %td= charity.tax_id
                %td= charity.name
                %td= charity.contact
                %td= charity.phone
                %td= charity.email
                %td= charity.website
                %td= charity.description
                %td
                  = link_to 'Edit', [:edit, charity], class: 'btn btn-default'
                  = link_to 'Invite', [:invite, charity], class: 'btn btn-warning'
                  = link_to 'Delete', charity_path(charity), class: 'btn btn-danger',:method=>:delete,:confirm=>"Arr you sure you want to delete charity?"

app/views/charities/info.html.haml
- content_for :body_class, 'charities info'
.gray
  .container
    .row
      .col-sm-12
        %h1 Top Charities
        .charities
          - @charities_slices.each_with_index do |charities, index|
            .row
              - charities.each_with_index do |charity, i|

                - if index == 0 and i == 2
                  .col-md-4
                    .signup_details
                      %h2 Add Your Charity
                      %ul
                        %li Free charity profile.
                        %li Free for athletes to create fundraisers for your charity.
                        %li Donations go directly to your account, minus applicable fees.
                      = link_to image_tag("add-your-charity-button.png"), new_charity_path, style: 'margin-right: 10px'
                      = link_to 'Details', '#details', class: 'details', data: { target: "#myModal", "toggle" => "modal"}
                - else
                  - if charity
                    .col-md-4
                      .charity
                        .image
                          .vertical_center
                            -if charity.logo.url.present?
                              = link_to image_tag(charity.logo.url(:profile)), charity
                            -else  
                              = link_to image_tag("charity-logo.jpg"), charity
                        .details
                          .name= link_to charity.name, charity


#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &#215;
        %h4#myModalLabel.modal-title Charity Details
      .modal-body
        %h3 About Frundraise
        %p 
          Frundraise is a fundraising website for athletes who want to support their favorite charity as part of their training for an event. Frundraise is all about being active, giving back, and training for something bigger than yourself. Training for and competing in an event like a marathon is one of the most difficult physical challenges many people will ever take on. Crossing the finish line is an accomplishment in itself, but Frundraise is about making it bigger than just that. When you add fundraising for a charity that is important to you or has made a difference in your life, and bring the support of your friends and family along, crossing that finish line on race day will be more rewarding than you could ever have imagined. 

        %p
          Frundraise is based in Colorado and was founded in 2013 by Nick Morrison. Nick is a runner and triathlete and first came up with the idea for Frundraise when he started planning his training for Ironman Wisconsin 2014. As part of his training, he wanted to start a fundraiser for a charity he is involved with called Friends of Amani which helps fund a children’s home in Tanzania for street orphans. When he attempted to start an online fundraiser, he was disappointed to find that there were no specialized websites for runners or triathletes and hence the idea for Frundraise was born.

        %h3 How it works

        %p
          When an athlete wants to start the first fundraiser to support you, they will set up their fundraiser profile on Frundraise and specify some contact information about the charity that they want to support. Using that contact information, the Frundraise team will reach out to the charity to let them know that the athlete is interested in supporting them. Once we reach out to you, you will be able to sign up for Frundraise and create a profile for your charity so that future athletes can support you as well. 

        %p
          When you create your charity’s profile, you will also need to create an account with Stripe. Stripe is the secure third-party credit card processor that Frundraise works with to process donations. Setting up your Stripe account allows the donations made through Frundraise to go directly to your charity’s bank account.

        %h3 Costs

        %p 
          Frundraise is free to use for everyone – athletes, charities, and supporters. When supporters make a donation, there is an applicable transaction fee and credit card processing fee.
        %ul
          %li For athletes? It is free to start a fundraiser on Frundraise. 
          %li For charities? It is free for charities to create their profile on Frundraise. 
          %li For supporters? It is free to support your athletes. The only cost is the amount of the donation that you decide to give. 

        %p 
          Frundraise charges a 5% transaction fee. This is the only revenue that Frundraise makes and it covers all of our expenses to stay in business. 
        %p
          Frundraise processes credit card donations through a third party organization called Stripe. Stripe charges a 2.9% + $0.30 per transaction fee for credit card processing. 

        %p Donation Example:
        %ul
          %li Donation amount: $50
          %li Amount that goes to charity: $45.75
          %li Transaction fee (to Frundraise): $2.50
          %li Credit Card processing fee (to Stripe): $1.75

      .modal-footer
        %a.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        = link_to 'Add Your Charity', new_charity_path, class: 'btn btn-primary'

app/views/charities/invite.html.haml
.gray.p30
  .container.white.r10
    .row
      = form_tag [:send_invite, @charity] do
        .col-sm-10
          %h1 New Charity Invite
          .form-group
            = label_tag :recipient
            = text_field_tag :recipient, @charity.email, class: 'form-control'
          .form-group
            = label_tag :body
            = text_area_tag :body, @message, class: 'form-control', style: 'height: 20em'
          = hidden_field_tag :athlete, @athlete
        .col-sm-2
          %br/
          = submit_tag 'Send Invite', class: 'btn btn-success btn-lg'
    %br/

app/views/charities/my.html.haml
.container
  .row
    .col-lg-12
      %table.table
        %tr

          %th Name
          %th Tax ID / EIN
          %th Website
          %th Address
          %th Phone
          %th Connected With Stripe
        - @charities.each do |charity|
          %tr
            %td= link_to charity.name, charity
            %td= charity.tax_id
            %td= charity.website
            %td= charity.address
            %td= charity.phone
            %td
              - if charity.connected_with_stripe?
                Connected
              - else
                Not connected
                = link_to 'Connect Now', [:connect_with_stripe, charity]

app/views/charities/new.html.haml
.gray.p30
  .container
    .row
      .col-sm-4.col-sm-offset-4.white.r10
        %h1.text-center Add Your Charity
        = render 'form'

app/views/charities/show.html.haml
- content_for :page_title, "#{@charity.name} | frundraise"

- if @can_edit
  - unless @charity.connected_with_stripe? 
    .publish_bar{ style: 'background: #32020f; color: white; padding: 10px;' }
      .container
        .pull-right
          = link_to 'Connect with Stripe',user_omniauth_authorize_path(:stripe_connect),class: "btn btn-success",:target => "_blank"
          

        %h4{ style: 'margin: 5px 0;'} Your charity is currently not connected with stripe. 
        / %div{ style: 'max-width: 650px;'}
        /   You can connect your chaarity with stripe
      
.gray.p30
  .container.white.r10.clearfix{style: "padding-bottom:15px"}
    .row
      %br
      .col-sm-3
        - if @charity.logo.profile.present?
          .image{ style: 'padding: 20px; border: solid 1px #ccc; margin-bottom: 10px; border-radius: 10px;' }
            = image_tag @charity.logo.profile.url, style: 'width: 100%; height: auto;'
        - else
          =image_tag("charity-logo.jpg",:style=>"background: gray;width: 100%; height: 200px;'")
          / .image{ style: 'background: gray; width: 100%; height: 200px;' }

        - if current_user.present? && @charity.user == current_user
          = form_for @charity,:html=>{:class=>"validate_form"} do |f|
            = f.file_field :logo, class: 'form-control required', style: 'margin-bottom: 5px;',"data-msg-required"=>"You must choose a new file before you can update the image"
            %br 
            = f.submit "Update Image", class: 'btn btn-primary'

        %br
        .social_media_links
          :erb
            <div class="fb-share-button" data-href="http://www.frundraise.com<%= charity_path(@charity) %>" data-type="button"></div>
            
            <a href="https://twitter.com/share" class="twitter-share-button" data-related="jasoncosta" data-lang="en" data-size="large" data-count="none">Tweet</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

            <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
            <g:plusone></g:plusone>

        .support-this-charity
          = link_to "Start Your Fundraiser",new_fundraiser_path(charity_id: @charity.id), class: 'btn btn-success'
      .col-sm-9
        %h1
          = best_in_place_if @can_edit, @charity, :name, type: :input        

        %h4 About The Charity
        = best_in_place_if @can_edit, @charity, :description, type: :textarea,:nil=>show_inline_story_heading(nil),:display_with => lambda {|v| show_inline_story_heading(v).html_safe}
        .website
          %a{:href=>@charity.website_url, :target=> '_blank'}Visit Website
          - if @charity.user == current_user
            = best_in_place_if @can_edit, @charity, :website, type: :input,:nil=> lambda {link_to "","#",:class=>"glyphicon glyphicon-edit"},:display_with => lambda {|v| link_to "","#",:class=>"glyphicon glyphicon-edit"}

          %h4 
            Amount Raised By Supporters: 
            = number_to_currency(@charity.raised)
    %br
    .row
      - if @fundraisers.present?
        %h4{style: "padding-left: 10px"} Active Fundraisers
      - @charity.fundraisers.published.active_event_fundraiser_donation.sort_by {|x| x.raised}.reverse.each do |fundraiser|
        %div.col-md-4{style: "padding-right: 100px;margin-top: 30px;"}
          %a.pull-left{:href=>fundraiser}
            - if fundraiser.image_url.present?
              %img.media-object{:src=>fundraiser.image.url(:profile),:style=>"width: 64px; height: 64px;"}
            -else  
              =image_tag("fundraiser-logo.png",:class=>"media-object",:style=>"width: 64px; height: 64px;")
          %div.media-body
            %h5.media-heading 
              =link_to fundraiser.name,fundraiser
            %div
              Event: 
              = "#{fundraiser.event.name} on #{fundraiser.event.happens_on.to_s(:long)}"  
            %div
              Fundraising Goal :
              - if fundraiser.goal.blank?
                Not Mentioned
              - else
                = number_to_currency(fundraiser.goal)
            %div
              Amount Raised:
              = number_to_currency(fundraiser.raised)
            %div
              Total Miles : 
              = pluralize(fundraiser.total_miles, 'Mile')     

app/views/charities/stripe_connected.html.haml
.container
  .row
    .col-lg-12
      %h1 Charity Now Connected With Stripe
      = link_to 'View Charity', @charity